name: eggai-examples
networks:
  eggai_example_network:
    driver: bridge
volumes:
  redpanda: null
services:
  redpanda:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.1
    container_name: redpanda
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - eggai_example_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "--brokers=redpanda:9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.8.0
    networks:
      - eggai_example_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console -config.filepath=${CONFIG_FILEPATH:-/tmp/config.yml}'
    environment:
      CONFIG_FILEPATH: ${CONFIG_FILEPATH:-/tmp/config.yml}
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8080:8080
    depends_on:
      redpanda:
        condition: service_healthy
  topic-init:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.1
    container_name: topic-init
    networks:
      - eggai_example_network
    depends_on:
      redpanda:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "
      echo 'Waiting for Redpanda cluster to be ready...' &&
      sleep 5 &&
      rpk topic create human --brokers=redpanda:9092 &&
      echo 'Topic humans created successfully!'" &&
      rpk topic create agents --brokers=redpanda:9092 &&
      echo 'Topic agents created successfully!'"
  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./dockerConfig/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318"
    networks:
      - eggai_example_network
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./dockerConfig/tempo.yaml:/etc/tempo.yaml
      - ./temp/tempo-data:/tmp/tempo
    ports:
      - "14268:14268"
      - "3200"
      - "4317:4317"
      - "9411:9411"
      - "16686"
    networks:
      - eggai_example_network
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./dockerConfig/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - eggai_example_network
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./dockerConfig/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dockerConfig/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json
      - ./dockerConfig/grafana-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    networks:
      - eggai_example_network