services:
  lmstudio:
    runtime: nvidia
    image: ghcr.io/eggai-tech/lm-studio:8
    environment:
      MODEL_NAME: gemma-3-4b-it-qat
      MODEL_PATH: /gemma-3-4B-it-QAT-Q4_0.gguf
      CONTEXT_LENGTH: 32768
    ports:
      - "1234:1234"
    networks:
      - eggai-example-network
