agents:
  audit:
    enabled: true
    replicaCount: 1
    environment: []
  billing:
    enabled: true
    replicaCount: 1
    environment: []
  claims:
    enabled: true
    replicaCount: 1
    environment: []
  escalation:
    enabled: true
    replicaCount: 1
    environment: []
  frontend:
    enabled: true
    replicaCount: 1
    environment: []
  policiesDocumentIngestion:
    enabled: true
    replicaCount: 1
    environment: []
  policies:
    enabled: true
    replicaCount: 1
    environment: []
  triage:
    enabled: true
    replicaCount: 1
    environment: []

image:
  repository: ghcr.io/eggai-tech/multi-agent-human-chat
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  limits:
    cpu: "250m"
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "10Gi"

cacheVolumeSize: "10Gi"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000
