global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:9464' ]
  
  - job_name: 'eggai-triage-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9091' ]
  
  - job_name: 'eggai-claims-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9092' ]
  
  - job_name: 'eggai-policies-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9093' ]
  
  - job_name: 'eggai-escalation-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9094' ]
  
  - job_name: 'eggai-billing-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9095' ]
  
  - job_name: 'eggai-audit-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9096' ]
  
  - job_name: 'eggai-frontend-agent'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:9097' ]
