demo_config:
  adapter_settings:
    filesystem:
      allowed_paths:
        - "./test_files"
        - "./logs"  
      max_file_size: "10MB"
      allowed_extensions: [".txt", ".md", ".json", ".yaml", ".py"]
    
  agent_settings:
    model: "openai/gpt-4o-mini"
    max_iterations: 5
    temperature: 0.1
    timeout: 30
    
  communication:
    transport: "kafka"
    bootstrap_servers: "localhost:19092"
    retry_attempts: 3
    
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "./logs/demo.log"