services:
  lmstudio:
    image: ghcr.io/eggai-tech/lm-studio:gemma-3-12B-it-qat-GGUF-1.0
    environment:
      MODEL_NAME: gemma-3-12B-it-qat
      MODEL_PATH: /gemma-3-12B-it-QAT-Q4_0.gguf
      CONTEXT_LENGTH: 32768
    ports:
      - "1234:1234"
    networks:
      - eggai-example-network
