model:
  n_classes: 5
  n_examples: null
  seed: [42, 47, 53]
  checkpoint_dir: checkpoints
  name: fewshot_baseline_n_all
dataset:
  paths:
    - /home/adrian/workspace/EggAI/examples/multi_agent_human_chat/agents/triage/data_sets/triage-training.jsonl
mlflow:
  tracking_uri: http://127.0.0.1:5001
  experiment_name: triage-model-training
  run_name: fewshot_baseline_n_all
