name: Build docker images

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build and push docker image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Github container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Genetare image tag
        id: image_tag
        run: |
          today=$(date -d@$(git show -s --format=%ct ${{ github.sha }}) +%Y%m%d%H%M%S)
          shortSha=$(git rev-parse --short=8 ${{ github.sha }})
          echo "tag=${shortSha}-${today}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: examples/multi_agent_human_chat
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/eggai-tech/multi_agent_human_chat:${{ steps.image_tag.outputs.tag }}
