name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "demo/helm/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Helm Chart Release 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push chart to GHCR
        run: |
          version=$(yq '.version' demo/helm/Chart.yaml)
          helm registry login ghcr.io/eggai-tech/multi_agent_human_chat/helm --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          helm package demo/helm --version ${version} --destination packaged
          helm push packaged/eggai-multi-agent-chat-${version}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
